#!/usr/bin/env bash


#######################################################################################################
## ██████  ███████ ██████  ██     ██ ███    ███        ██████  ██████  ███    ██ ███████ ██  ██████  ##
## ██   ██ ██      ██   ██ ██     ██ ████  ████       ██      ██    ██ ████   ██ ██      ██ ██       ##
## ██████  ███████ ██████  ██  █  ██ ██ ████ ██ █████ ██      ██    ██ ██ ██  ██ █████   ██ ██   ███ ##
## ██   ██      ██ ██      ██ ███ ██ ██  ██  ██       ██      ██    ██ ██  ██ ██ ██      ██ ██    ██ ##
## ██████  ███████ ██       ███ ███  ██      ██        ██████  ██████  ██   ████ ██      ██  ██████  ##
#######################################################################################################                                             

#-------- Bspwm config directory ---------------#
BSPDIR="$HOME/.config/bspwm"

#-------- Externals ---------------#
$BSPDIR/rules &
$BSPDIR/startup &
$BSPDIR/works &

#-------- Export bspwm/bin dir to PATH -----------#
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'
export _JAVA_AWT_WM_NONREPARENTING=1 # Run java applications without issues

#-------- Variables and Config -----------------#
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

#--------- custom configs -----------------------#
bspc config pointer_motion_interval 5

#---------- Bspwm colors ------------------------#
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color15"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#BSPWM_FBC='#A1AFC9'
BSPWM_NBC='#2E3440'
#BSPWM_ABC='#B48EAD'
#BSPWM_PFC='#A3BE8C'

## Bspwm appearance
BSPWM_BORDER='1'
BSPWM_GAP='4'
BSPWM_SRATIO='0.50'

# Kill if already running
killall -9 xsettingsd dunst ksuperkey xfce4-power-manager bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	# /usr/lib/xfce-polkit/xfce-polkit &
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &