#!/usr/bin/env bash

####################################
## ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗ ##
## ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗ ##
## ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝ ##
####################################

for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    #bspc monitor "$monitor" -d '   ' '   ' '   ' '   ' '   ' '  ' '   ' '   ' '  '
    bspc monitor "$monitor" -d ' ' ' ' ' ' ' ' ' ' ' '
done

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
    xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of eDP1
    # Workspaces
    #bspc monitor HDMI-1 -d 
    #V VI VII VIII
else
    xrandr --output HDMI-1 --off
    # Remove nodes
    while bspc node @V: --kill; do
        :
    done
    while bspc node @VI: --kill; do
        :
    done
    while bspc node @VII: --kill; do
        :
    done
    while bspc node @VIII: --kill; do
        :
    done
    # Remove workspaces
    bspc desktop -r V VI VII VIII
    # Remove monitor
    bspc monitor HDMI-1 -r
fi
## Manage all the unmanaged windows remaining from a previous session.
# bspc wm --adopt-orphans
