#!/usr/bin/env bash

bash ~/.config/picom/launch.sh

# bspwm directory
#DIR="$HOME/.config/picom/"

# Terminate if picom is already running
#killall -q picom

# Wait until the processes have been shut down
#while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

# Launch picom
#picom --animations --animation-for-open-window zoom --animation-clamping -b --config "$DIR"/picom.conf &
